#!/bin/bash
set -e

module=$(git remote get-url ssh | sed 's/.*\///' | sed 's/\.git//')
v=$(git describe)

s3d-flow-down() {
  sed -i "s/$module?ref=.*\"/$module?ref=$v\"/" *.tf
  s3d-flow
}

(cd ../aws-ec2 && s3d-flow-down)
